### ISSUE TITLE
Megaterm

### ISSUE THREAD

**Issue by chi7ed** [wmBolles/MTP#6]
Hi  @wmBolles  

### important : we have a lot of things to solve and change in the game such as the args after ./play 
we need to upgrade it to become like : ``` ./play up[6] ```
``` up[5] = up up up up up. ```
### 2 : give the possibility to the user to chose the character  
the future command : ``` ./play 'character' up[n] left[n].... ```

**Comment by wmBolles** [comment]
@chi7ed 

### good idea 

i think that you have a lot of time to solve all issues 

> Hi @wmBolles
> 
> ## I use python3 command to run *.py files. but how can i get the executable.
> ### important : we have a lot of things to solve and change in the game such as the args after ./play
> we need to upgrade it to become like : `./play up[6]` `up[5] = up up up up up.`
> 
> ### 2 : give the possibility to the user to chose the character
> the future command : `./play 'character' up[n] left[n]....`

**Comment by chi7ed** [comment]
> @chi7ed
> ### good idea
> 
> i think that you have a lot of time to solve all issues
> 
> > Hi @wmBolles
> > ## I use python3 command to run *.py files. but how can i get the executable.
> > ### important : we have a lot of things to solve and change in the game such as the args after ./play
> > we need to upgrade it to become like : `./play up[6]` `up[5] = up up up up up.`
> > ### 2 : give the possibility to the user to chose the character
> > the future command : `./play 'character' up[n] left[n]....`

I think that WE have the time to fix all issues together !

**Comment by wmBolles** [comment]
hada rah smiyto github not whatsapp

**Comment by chi7ed** [comment]
sorry
